name: Bug Report Form (Beta)
description: Bug report for the Jupyter Extension for VS Code
labels: [bug, needs-triage]
assignees:
  - octocat
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out this bug report!
- type: checkboxes
  id: feature-focus
  attributes:
    label: How are you mainly using the Jupyter extension?
    options:
      - label: Notebooks (.ipynb)
      - label: Interactive Window and or Cell Scripts (ex. .py files with \#%%)
      - label: Both
- type: textarea
  id: what-happened
  attributes:
    label: What happened?
    description: What did you expect to happen?
    placeholder: Tell us what happened or didn't happen!
  validations:
    required: true
- type: dropdown
  id: vscode-flavor
  attributes:
    label: What flavor of VS Code are you using?
    multiple: true
    options:
      - Stable
      - Insiders
  validations:
    required: true
- type: textarea
  id: jupyter-version
  attributes:
    label: Jupyter Extension Version
    description: What version of the Jupyter extension are you using?
    placeholder: The version can be found at the top of the extension's description in the extensions sidebar.
  validations:
    required: true
- type: textarea
  id: logs
  attributes:
    label: Jupyter logs
    description: Please copy and paste all of the text in the Jupyter Output panel. 
    placeholder: This can really help us a lot to understand what may have gone wrong!
    render: shell
- type: markdown
  attributes:
    value: |
      ---
      ## The following fields are optional but can help us make a better determination of what may have gone wrong.
- type: dropdown
  id: coding-language
  attributes:
    label: What coding language are you working with?
    multiple: true
    options:
      - Python
      - SQL
      - R
      - Julia
      - C#
- type: textarea
  id: python-extension-version
  attributes:
    label: Python Extension Version
    description: If using Python, what version of the extension are you using?
    placeholder: The version can be found at the top of the extension's description in the extensions sidebar.
  validations:
    required: false
- type: textarea
  id: vscode-version
  attributes:
    label: VS Code Version?
    description: What version of VS Code are you using?
    placeholder: You can copy the contents of Help > About and paste here.
- type: textarea
  id: python-version
  attributes:
    label: Python Version
    description: What version of Python are you using?
  validations:
    required: false
- type: textarea
  id: anaconda-version
  attributes:
    label: Anaconda Version
    description: If applicable, what version of the Anaconda are you using?
  validations:
    required: false
- type: dropdown
  id: os
  attributes:
    label: What OS are you running on?
    multiple: true
    options:
      - Linux distro
      - Mac
      - Windows
      - Browser
  validations:
    required: false
- type: dropdown
  id: local-remote
  attributes:
    label: Running Jupyter locally or remotely?
    multiple:
    options:
      - Local
      - Remote
      - N/A or Not sure
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/microsoft/vscode-jupyter/blob/main/CODE_OF_CONDUCT.md)
    options:
      - label: I agree to follow this project's Code of Conduct
        required: true
